set(SRC_FILES
    App.cpp
    ArcaneNovaWeapon.cpp
    BatEnemy.cpp
    BruteEnemy.cpp
    Enemy.cpp
    EnemyDirector.cpp
    EliteEnemy.cpp
    ExperienceGem.cpp
    FloatingText.cpp
    GameScene.cpp
    GlyphObject.cpp
    Hud.cpp
    MagicBoltWeapon.cpp
    Player.cpp
    PlayerMarker.cpp
    Projectile.cpp
    RewardChest.cpp
    SlimeEnemy.cpp
    Upgrade.cpp
    UpgradeManager.cpp
    WeaponInventory.cpp
)

set(INCLUDE_FILES
    App.hpp
    ArcaneNovaWeapon.hpp
    BatEnemy.hpp
    BruteEnemy.hpp
    Character.hpp
    Enemy.hpp
    EnemyDirector.hpp
    EliteEnemy.hpp
    ExperienceGem.hpp
    FloatingText.hpp
    GameScene.hpp
    GlyphObject.hpp
    Hud.hpp
    MagicBoltWeapon.hpp
    Player.hpp
    PlayerMarker.hpp
    Projectile.hpp
    RewardChest.hpp
    SlimeEnemy.hpp
    SpriteAssets.hpp
    Upgrade.hpp
    UpgradeManager.hpp
    Weapon.hpp
    WeaponInventory.hpp
)

set(TEST_FILES
)
